In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((2,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [28]:
np.linspace(0,20,20)

array([  0.        ,   1.05263158,   2.10526316,   3.15789474,
         4.21052632,   5.26315789,   6.31578947,   7.36842105,
         8.42105263,   9.47368421,  10.52631579,  11.57894737,
        12.63157895,  13.68421053,  14.73684211,  15.78947368,
        16.84210526,  17.89473684,  18.94736842,  20.        ])

In [15]:
np.eye(4) #identity matrix, a 2-dim square matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [29]:
np.random.rand(5)

array([ 0.66365354,  0.15968687,  0.43598396,  0.67267752,  0.35141169])

In [32]:
np.random.randn(4,4)

array([[ 0.47757272, -0.23268284, -1.3365352 , -1.25535627],
       [ 0.4263134 , -0.60213481,  0.62482833, -1.95007197],
       [ 0.14202983,  2.28664967,  0.82728289,  0.48084359],
       [ 0.66348477, -0.84646697,  0.16134865,  1.94885664]])

In [35]:
np.random.randint(1,100,10)

array([85, 83, 71, 22, 10, 31, 12, 54, 25,  2])

In [36]:
arr = np.arange(25)

In [38]:
ranarr = np.random.randint(0,50,10)

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr.max()

49

In [41]:
ranarr.min()

0

In [42]:
ranarr.argmax()

1

In [43]:
ranarr.argmin()

7

In [44]:
arr = arr.reshape(5,5)

In [46]:
arr.shape

(5, 5)

In [48]:
arr.dtype

dtype('int32')

In [49]:
from numpy.random import randint

In [50]:
randint(0,49)

1