In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[:5] = 99 #broadcast the value

In [8]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.arange(0,11)

In [11]:
slice_of_arr = arr[0:6] #reference to the first five elements

In [17]:
arr_copy = arr.copy() #shallow copy

In [14]:
arr_copy[:] = 100

In [15]:
print(arr_copy)

[100 100 100 100 100 100 100 100 100 100 100]


In [16]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[1,2] #index slicing

30

In [28]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [29]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [31]:
bool_arr = arr > 4 #conditional selection

In [32]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [35]:
arr_2d = np.arange(50).reshape(5,10)

In [36]:
arr_2d #index slicing practice

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])